export const ALL_PRODUCT = "ALL_PRODUCT";
export const SINGLE_PRODUCT = "SINGLE_PRODUCT";
export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const DELETE_PRODUCT = 'DELETE_PRODUCT'

export const ALL_CATEGORIES = 'ALL_CATEGORIES';
export const CREATE_CATEGORY = 'CREATE_CATEGORY';
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';


export const TOKEN = "TOKEN";
export const LOGIN = "LOGIN";
export const UPDATE_USER = 'UPDATE_USER'
export const LOGOUT = 'LOGOUT'
export const EMAIL = 'EMAIL'
export const OTP = 'OTP'

export const CREATE_NEW_ADDRESS = 'CREATE_NEW_ADDRESS';
export const GET_USER_ADDRESS = 'GET_USER_ADDRESS';
export const UPDATE_USER_ADDRESS = 'UPDATE_USER_ADDRESS';
export const DELETE_USER_ADDRESS = 'DELETE_USER_ADDRESS';
export const SET_DEFAULT_ADDRESS = 'SET_DEFAULT_ADDRESS';
export const GET_DELIVERY_ADDRESS = 'GET_DELIVERY_ADDRESS';

export const DISCOUNT = 'DISCOUNT';
export const CREATE_COMMENT = 'CREATE_COMMENT'
export const UPDATE_COMMENT = 'UPDATE_COMMENT'
export const DELETE_COMMENT = 'DELETE_COMMENT'


export const CREATE_ACCESSORY = 'CREATE_ACCESSORY';
export const UPDATE_ACCESSORY = 'UPDATE_ACCESSORY';
export const DELETE_ACCESSORY = 'DELETE_ACCESSORY';

export const GET_DATA = 'GET_DATA'
export const INIT_DATA = 'INIT_DATA'

export const ERROR_MESSAGE = 'ERROR_MESSAGE'

export const ALL_CART = 'ALL_CART'
export const ADD_TO_CART = 'ADD_TO_CART'
export const REMOVE_CART = 'REMOVE_CART'

export const CREATE_NEW_ORDER = 'CREATE_NEW_ORDER'
export const GET_ORDER_USER = 'GET_ORDER_USER'
export const GET_ORDER_DETAIL = ' GET_ORDER_DETAIL'
export const UPDATE_STATUS_PAYMENT = 'UPDATE_STATUS_PAYMENT'
export const UPDATE_ORDER_ADMIN = 'UPDATE_ORDER_ADMIN'
export const LIST_USER = 'LIST_USER'
export const GET_ORDER_USER_ADMIN = 'GET_ORDER_USER_ADMIN'
